Don't boot server, scheduler and worker without REDASH_SECRET_KEY.

diff --git a/bin/docker-entrypoint b/bin/docker-entrypoint
--- a/bin/docker-entrypoint
+++ b/bin/docker-entrypoint
@@ -2,6 +2,11 @@
 set -e
 
 worker() {
+  if [ "x${REDASH_SECRET_KEY}" = "x" ]; then
+    echo "ERROR: REDASH_SECRET_KEY is required."
+    exit 1
+  fi
+
   WORKERS_COUNT=${WORKERS_COUNT:-2}
   QUEUES=${QUEUES:-queries,scheduled_queries,celery,schemas}
 
@@ -10,6 +15,11 @@ worker() {
 }
 
 scheduler() {
+  if [ "x${REDASH_SECRET_KEY}" = "x" ]; then
+    echo "ERROR: REDASH_SECRET_KEY is required."
+    exit 1
+  fi
+
   WORKERS_COUNT=${WORKERS_COUNT:-1}
   QUEUES=${QUEUES:-celery}
   SCHEDULE_DB=${SCHEDULE_DB:-celerybeat-schedule}
@@ -20,6 +30,11 @@ scheduler() {
 }
 
 server() {
+  if [ "x${REDASH_SECRET_KEY}" = "x" ]; then
+    echo "ERROR: REDASH_SECRET_KEY is required."
+    exit 1
+  fi
+
   exec /usr/local/bin/gunicorn -b 0.0.0.0:5000 --name redash -w${REDASH_WEB_WORKERS:-4} redash.wsgi:app
 }
 
@@ -41,11 +56,11 @@ verify() {
 
 reencrypt () {
   if [ "x${REDASH_SECRET_KEY}" = "x" ]; then
-    echo "ERROR: REDASH_SECRET_KEY required."
+    echo "ERROR: REDASH_SECRET_KEY is required."
     exit 1
   fi
   if [ "x${VARANUS_REDASH_OLD_SECRET_KEY}" = "x" ]; then
-    echo "ERROR: VARANUS_REDASH_OLD_SECRET_KEY required."
+    echo "ERROR: VARANUS_REDASH_OLD_SECRET_KEY is required."
     exit 1
   fi
 
